name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: SSH Deploy to server
        run: |
          echo "Deploy started!"
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 21098 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'cd public_html/ && git pull origin main  && php artisan migrate --force && composer install && php artisan cache:clear && php artisan optimize && php artisan config:clear'
          echo "Deploy finished!"
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
