name: CI/CD Deploy

# Запуск workflow при пуші в main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Перевірка коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Встановлення sshpass для підключення через пароль
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Крок 3: Підключення до сервера через SSH з портом і виконання команд
      - name: SSH Deploy to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 21098 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'cd public_html/ && git pull origin main && php artisan cache:clear && php artisan optimize && php artisan config:clear && php artisan migrate --force && composer install'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
